name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2
  hihi

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0 # ✅ Moved to the correct position
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  youtube_player_flutter: 9.1.1
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # ✅ Corrected version

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
